export { Header } from './Header/Header.component'
export { Banner } from './Banner/Banner.component'
export { ShopNow } from './ShopNow/ShopNow.component'
export { Shows } from './Shows/Shows.component'
export { Footer } from './Footer/Footer.component'